name: faviorite_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_bloc:
  dio:
  cupertino_icons:
  url_launcher:
  flutter_secure_storage:
  equatable:
  flutter_svg:
  pin_code_fields:
  google_sign_in:
  carousel_slider:
  shimmer:
  google_mobile_ads:
  intl: ^0.19.0
  encrypt:
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash:
  change_app_package_name:
  flutter_lints:
  flutter_launcher_icons:

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/appIcon.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21
#  web:
#    generate: true
#    image_path: "path/to/image.png"
#    background_color: "#hexcode"
#    theme_color: "#hexcode"
#  windows:
#    generate: true
#    image_path: "path/to/image.png"
#    icon_size: 48 # min:48, max:256, default: 48
#  macos:
#    generate: true
#    image_path: "path/to/image.png"


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Thin.ttf
          weight: 100
        - asset: fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: fonts/Poppins-Light.ttf
          weight: 300
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: fonts/Poppins-Black.ttf
          weight: 900
    - family: PilatExtended
      fonts:
        - asset: fonts/PilatExtended-Heavy.ttf
          weight: 900
        - asset: fonts/PilatExtended-Regular.ttf
          weight: 400
        - asset: fonts/PilatExtended-Bold.ttf
          weight: 600
    - family: TipsActivityLogo
      fonts:
        - asset: fonts/TipsActivityLogo.ttf
flutter_native_splash:
  color: "#ffffff"
  image: assets/splashLogo.png


  color_dark: "#181818"
  image_dark: assets/splashLogoDark.png

  android_12:
    color: "#ffffff"
    image: assets/splash_twelve.png
    image_dark: assets/splash_twelveDark.png
    color_dark: "#181818"
  android: true
  ios: false
  web: false