// List<String> specialTipsNames = [
//   "Today's Top 3 Tips👑",
//   "Single Game👑",
//   "Over-Under👑",
//   "Football Combine👑",
//   "Basketball👑",
//   "Double Game👑",
//   "20+ odds👑",
//   "Tennis👑",
//   "Elite Tips👑",
//   "Fixed Tips👑",
//   "Daily 10+👑",
//   "HT-FT 👑",
//   "Single + Double👑",
// ];
// List<String> specialTipsEndPoint = [
//   "Today's Top 3 Tips",
//   "Single Game",
//   "Over-Under",
//   "Football Combine",
//   "Basketball",
//   "Double Game",
//   "Today's 20+ odds",
//   "Tennis",
//   "Elite VIP",
//   "Fixed VIP",
//   "Daily 10+ Odds VIP",
//   "HT-FT VIP",
//   "Single VIP + Double VIP",
// ];
