/// Flutter icons TipsActivityLogo
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
// flutter:
//   fonts:

///
///
///
import 'package:flutter/widgets.dart';

class TipsActivityLogo {
  TipsActivityLogo._();

  static const _kFontFam = 'TipsActivityLogo';
  static const String? _kFontPkg = null;

  static const IconData tipsactivitylogo =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
